### ISSUE TITLE
ticks is supported in type=chart

### ISSUE THREAD

**Issue by rodionos** [axibase/charts-language-service#25] opened 2019-08-23 10:48 UTC
```
ticks = 8
```

It works for type = chart however validator highlights it as a warning.
On the other hand, ticks-rotate is not supported in type=chart but there is no warning shown if this setting is present.

![image](https://user-images.githubusercontent.com/2098022/63587335-64574b00-c5ac-11e9-838f-c9c6ec1d8ba6.png)

**Comment by PolinaShneider** [comment] 2019-08-23 12:36
@rodionos could you provide a test config to investigate the problem?

**Comment by rodionos** [comment] 2019-08-23 12:39
It's a protected example that I prefer to share on github. Create any chart, add ticks.

**Comment by PolinaShneider** [comment] 2019-08-23 12:51
Does this example from documentation work for you? 
`type = chart`
`ticks` gives no warning: https://apps.axibase.com/chartlab/5e968be4

**Comment by rodionos** [comment] 2019-08-23 13:04
![image](https://user-images.githubusercontent.com/2098022/63594628-a63dbc80-c5bf-11e9-800f-e90e292f36b2.png)

**Comment by annstriganova** [comment] 2019-08-23 13:17
Can not reproduce too. Moreover, this rule was replaced in PR [375](https://github.com/axibase/axibase-charts-vscode/pull/375):
https://github.com/axibase/charts-language-service/commit/d832a2345880134c4c3801df926e263bad013bdf#diff-5e79d2e01810dd3afa0ce74e0ef7de86
![Selection_001](https://user-images.githubusercontent.com/20650874/63595297-40523480-c5c1-11e9-8606-b77b051f338d.png)

@PolinaShneider, could it be some cache problem with specific browser version?

**Comment by PolinaShneider** [comment] 2019-08-23 13:20
Checked in Firefox 68.0.2 — also no warning

**Comment by VeselovAlex** [comment] 2019-08-23 13:57
Looks like a cache issue, try to clear cache by going to `developer tools -> network -> Disable cache` rather than reload page with Cmd+Shift.

<img width="501" alt="изображение" src="https://user-images.githubusercontent.com/3617329/63597893-1b60c000-c5c7-11e9-9612-ba75574b1bb6.png">

**Comment by rodionos** [comment] 2019-08-23 14:19
![image](https://user-images.githubusercontent.com/2098022/63599378-26691f80-c5ca-11e9-858d-b7eec77c76e1.png)

**Comment by annstriganova** [comment] 2020-01-11 11:36
Please, re-open, if issue will be reproduced again.

**Closed by annstriganova** 2020-01-11 11:36 UTC
Labels: done
